spring:
  application:
    name: account
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/account
    username: user
    password: password
  docker:
    compose:
      enabled: true
      file: account/compose.yaml
  sql:
    init:
      mode: always
