services:
  valkey:
    image: valkey/valkey:latest
    container_name: ksbp-sse-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["valkey-server", "--appendonly", "yes"]
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
