[versions]
kotlin = "2.3.0"
ktlint-gradle = "14.0.1"
pinterest-ktlint = "1.6.0"
jdk = "25"
spring-boot = "4.0.1"
spring-boot-start-aop = "4.0.0-M2"
spring-boot-starter-kotlin-serialization = "4.0.0"
spring-dependency-management = "1.1.7"
exposed = "1.0.0-rc-4"
h2 = "2.4.240"
r2dbc-h2 = "1.1.0.RELEASE"
okhttp3 = "5.3.2"
apache-httpclient5 = "5.6"
kotlinx-coroutines = "1.10.2"
ulid-kotlin = "1.5.0"
reactor-kafka = "1.3.25"
apache-kafka = "4.1.1"
fasterxml-jackson = "2.20.1"
tools-jackson = "3.0.3"
kotlinx-serialization = "1.10.0-RC"
kotlinx-serialization-jvm-extra = "0.2.0"
gson = "2.13.2"
jackson-dataformat-msgpack = "0.9.10"
google-protobuf = "4.33.2"
protobuf-gradle-plugin = "0.9.6"
mockk = "1.14.7"

jjwt = "0.13.0"
r2dbc-postgresql = "1.1.1.RELEASE"

[plugins]
# Kotlin JVM Gradle plugin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }

# Spring Boot plugin
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

# Spring dependency management plugin
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

# ktlint Gradle plugin
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }

# Protobuf
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }

[libraries]

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "spring-boot-start-aop" }

# Reactor
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
reactor-test = { module = "io.projectreactor:reactor-test" }

spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }

spring-boot-starter-kafka = { module = "org.springframework.boot:spring-boot-starter-kafka" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }

# Serialization
spring-boot-starter-kotlin-serialization = { module = "org.springframework.boot:spring-boot-starter-kotlin-serialization", version.ref = "spring-boot-starter-kotlin-serialization" }

jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "fasterxml-jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "fasterxml-jackson" }
jackson-dataformat-msgpack = { module = "org.msgpack:jackson-dataformat-msgpack", version.ref = "jackson-dataformat-msgpack" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "google-protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "google-protobuf" }

tools-jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "tools-jackson" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-jvm-extra = { module = "io.github.bossm0n5t3r:kotlinx-serialization-jvm-extra", version.ref = "kotlinx-serialization-jvm-extra" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2", version.ref = "r2dbc-h2" }

spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }

okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "apache-httpclient5" }

kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

ulid-kotlin = { module = "com.aallam.ulid:ulid-kotlin", version.ref = "ulid-kotlin" }

reactor-kafka = { module = "io.projectreactor.kafka:reactor-kafka", version.ref = "reactor-kafka" }
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "apache-kafka" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version.ref = "r2dbc-postgresql" }
spring-boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
