services:
  postgres:
    image: postgres:18-alpine
    container_name: ksbp-account-postgres
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
